import type { PolicyTemplateSet } from "../types.js";
import { sharedClauses } from "./shared/legal-terms.js";

export const privacyPolicyTemplate: PolicyTemplateSet = {
  en: {
    id: "privacy-policy",
    title: "{{productName}} Privacy Policy",
    sections: [
      {
        id: "introduction",
        heading: "Introduction",
        body:
          "{{companyName}} (\"we\", \"us\", or \"our\") operates {{productName}}. This Privacy Policy " +
          "explains what information we collect, how we use it, and the choices you have.",
      },
      {
        id: "information-we-collect",
        heading: "Information We Collect",
        requiresProductInput: true,
        body:
          "We collect information you provide directly to us (such as your name and email address when " +
          "you create an account), information generated by your use of {{productName}}, and limited " +
          "technical information (such as device and browser type) needed to operate and secure the service.",
      },
      {
        id: "how-we-use-information",
        heading: "How We Use Information",
        body:
          "We use collected information to provide and improve {{productName}}, communicate with you " +
          "about your account or updates, maintain the security and integrity of the service, and comply " +
          "with legal obligations.",
      },
      {
        id: "analytics",
        heading: "Analytics",
        requiresProductInput: true,
        body:
          "We may use privacy-conscious analytics to understand aggregate usage of {{productName}} and " +
          "improve it over time. We do not sell your personal information.",
      },
      {
        id: "data-sharing",
        heading: "Data Sharing",
        requiresProductInput: true,
        body:
          "We do not share your personal information with third parties except: with service providers " +
          "who help us operate {{productName}} under confidentiality obligations, when required by law, " +
          "or with your consent.",
      },
      {
        id: "data-retention",
        heading: "Data Retention",
        requiresProductInput: true,
        body:
          "We retain your information for as long as your account is active or as needed to provide " +
          "{{productName}}, comply with legal obligations, resolve disputes, and enforce our agreements.",
      },
      {
        id: "your-rights",
        heading: "Your Rights",
        requiresProductInput: true,
        body:
          "Depending on your location, you may have the right to access, correct, export, or delete your " +
          "personal information. To exercise these rights, contact us at {{contactEmail}}.",
      },
      {
        id: "account-deletion",
        heading: "Account Deletion",
        requiresProductInput: true,
        body: sharedClauses.accountDeletionPlaceholder,
      },
      {
        id: "security",
        heading: "Security",
        requiresProductInput: true,
        body: sharedClauses.securityPlaceholder,
      },
      {
        id: "childrens-privacy",
        heading: "Children's Privacy",
        requiresProductInput: true,
        body: sharedClauses.childrensPrivacy,
      },
      {
        id: "changes",
        heading: "Changes to This Policy",
        body:
          "We may update this Privacy Policy from time to time. We will post the updated version here " +
          "with a new effective date.",
      },
      {
        id: "contact",
        heading: "Contact Us",
        body: "If you have questions about this Privacy Policy, contact us at {{contactEmail}}.",
      },
    ],
  },
};
